### ISSUE TITLE
能支持一下本地模型吗？

### ISSUE THREAD

**Issue by Lee-7723** [HCLonely/live2d.user.js#1]
或者其他形式的自定义模型，live2d
想在OBS直播里加一个看板娘，找到个PPet，但是看起来作者也是用的chromium环境，chromium系需要把硬件加速关掉才能被OBS捕捉，PPet我不会用调试关硬件加速。

**Comment by HCLonely** [comment]
这个寒假可能会做，也可能咕咕咕

**Comment by HCLonely** [comment]
https://github.com/HCLonely/live2dNodeApi
