### ISSUE TITLE
live2d网页版看板娘1.28更新问题

### ISSUE THREAD

**Issue by mesansan** [HCLonely/live2d.user.js#7]
live2d网页版看板娘我1.28更新好后工具栏\e62e问题依然存在
并且模型也不显示了切换模型也没有用
退回1.2.7就可以显示模型。
恳请大佬有时间修复一下这个问题 感谢大佬

**Comment by HCLonely** [comment]
已修复

**Comment by mesansan** [comment]
感谢大佬
